{
    email: 'cultural1.program@gmail.com',
    password: 'cultur@123?',
    name: 'CULTURAL PROGRAM PARTICPANT GIFTS',
    description: "<p>Cultural Program Youth Partipants and College Teams&nbsp;- pick up your gift here.</p> ",
    stallName: 'CUL-2',
    vendorCategoryId:5,
  },
{
    email: 'taste1.india@gmail.com',
    password: 'tastei@123?',
    name: 'TASTE OF INDIA COUPONS',
    description: "<p>Buy Coupons for food and carnival games.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cash or credit cards.</p> ",
    stallName: 'T-1',
    vendorCategoryId:5,
  },
{
    email: 'hindu.temple@gmail.com',
    password: 'hindut@123?',
    name: 'HINDU TEMPLE OF HAMPTON ROADS & COMMUNITY CENTER',
    description: "<p>Become a HTOHR member. Register for mailing list. Learn about various programs and activities avilable through the Community Center and its various groups:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Balakendra -&nbsp;&nbsp;children education&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*YogaTherapy&nbsp;- for all ages&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*JeevanSandhya Mandal - activities for seniors&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Hampton Roads Cricket Organization - amatteur cricket club.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*GujaratiSamaj - encourage Gujarati culture and heritage</p>",
    stallName: 'D-E-F',
    vendorCategoryId:3,
  },
{
    email: 'tasteg.india@gmail.com',
    password: 'tastei@123?',
    name: 'TASTE OF INDIA GUEST SERVICES LOST & FOUND',
    description: "<p><p>VOLUNTEER CHECK-IN</p>;<p>Taste of India Control Center - information, Lost &amp; Found. All ToI Volunteers Check-in here.</p><p>&nbsp;FREE HEALTH CAMP REGISTRATION</p><p>Register for Free Health Camp on May 20. Sponsored by American Association of Indian Origin (AAPI)- Hampton Roads and Taste of India .</p><p>India Heritage Foundation.</p><p>Learn how Indian Heritage Foundation helps the community.</p></p>",
    stallName: 'R-2',
    vendorCategoryId:5,
  },
{
    email: 'mehendi1234@gmail.com',
    password: 'mehend@123?',
    name: 'EYEBROWS THREADING',
    description: "<p>Shape your eyebrows painlessly the Indian way. $10 and up. (Nocoupons)</p>",
    stallName: 'V-2',
    vendorCategoryId:3,
  }
